[project]
name = "demo-ai-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autogen-agentchat>=0.4.4",
    "autogen-ext[azure,openai]>=0.4.4",
    "python-dotenv>=1.0.1"
]
